### ISSUE TITLE
Unable to use the 'Enter' key to confirm a keycode selection

### ISSUE THREAD

**Issue by RobertWCarey** [nickcoutsos/keymap-editor#111]
After selecting a new key I will use tab to jump to the "confirm" button and the press enter. However, nothing happens until I click the button with my cursor.

![image](https://github.com/nickcoutsos/keymap-editor/assets/38249951/704c4ad4-df5d-4698-a94e-a54eeb11a909)

**Comment by nickcoutsos** [comment]
Thanks!

I can reproduce the issue and have pinpointed the source (a key event handler is inappropriately consuming the _Enter_ keypress to select the highlighted key from the list), but in the middle of some work that touches on this and won't be able to deploy a fix as quickly as I'd like.

As a temporary workaround you can also press _Space_ to trigger the focused button element, but I'll keep this issue open and update you once it's properly resolved.

**Comment by nickcoutsos** [comment]
Alright, well, my other task ended up being too complex to tackle at once so I wrapped it up and put in a quick fix for this issue. Thank you again for sharing!
