### ISSUE TITLE
Can't find hold tap behavior

### ISSUE THREAD

**Issue by glyh** [nickcoutsos/keymap-editor#116]
![image](https://github.com/nickcoutsos/keymap-editor/assets/12870742/c04da458-64f8-42b4-b4d5-e656a20f6a23)

**Comment by glyh** [comment]
NVM I'm silly

**Comment by nickcoutsos** [comment]
I just noticed that the selector dialog's prompt is wrong, and I'm not sure when that would have been broken. So thank you for sharing that screenshot!

**Comment by OlofHarrysson** [comment]
I'm not finding it. Would appreciate some help

**Comment by nickcoutsos** [comment]
Hi @OlofHarrysson, you can think of hold-tap more like a "behavior type". Normally you would use a predefined behavior like mod-tap (`&mt`) or layer-tap (`&lt`). If you need something more specific you can create a new hold-tap behavior.
