### ISSUE TITLE
why is the main branch so out of date?

### ISSUE THREAD

**Issue by laundmo** [nickcoutsos/keymap-editor#118]
the note in the readme just states that it is out of date, but not why.

i would appreciate a explanation of why the pages branch is just obfuscated/minified and the main one is out of date? is this project just not open source anymore?

Ideally such a explanation should be in the readme.

**Comment by nickcoutsos** [comment]
Sorry to trouble you. For simplicity you may consider the GitHub Pages build to be a preview of the project that remains closed source for the moment. I'll update the readme when I have an opportunity.

**Comment by nmder** [comment]
Thanks for sharing the great work!

Any plans of making the page opensource?
