### ISSUE TITLE
Fix: Argless Behaviours in hold-tap

### ISSUE THREAD

**Issue by TheSast** [nickcoutsos/keymap-editor#119]
Currently, putting a `mod-morph` or `macro` inside a `hold-tap` will result in the editor complaining about a missing parameter (thus preventing it's use). 

Manually modifying the ZMK layout as specified by the [docs](https://zmk.dev/docs/behaviors/hold-tap#using-different-behavior-types-with-hold-taps) by adding a dummy parameter will fix the complaint and will make the `hold-tap` work correctly.

**Comment by nickcoutsos** [comment]
It should add placeholders automatically when its able to detect them. Can you provide an example? It's possible some of my experimental support for parameterized macros has unintentionally impacted this.

**Comment by TheSast** [comment]
I hope this video can show it well enough:

https://github.com/nickcoutsos/keymap-editor/assets/27977196/922ec05d-40e6-48c8-9ab8-7fa0cea50c93

**Comment by nickcoutsos** [comment]
Oof! Ok, thanks for the heads up! I'll try to take a closer look as soon as I have some time to myself this weekend.

**Comment by nickcoutsos** [comment]
@TheSast haven't tested extensively but it looks like the issue was strictly in how the "incomplete" binding is detected despite placeholders being set correctly. I've put in a fix for that, when you have a chance to try it again please let me know if that resolves the issue.

**Comment by TheSast** [comment]
@nickcoutsos it seems to be working for me now! 🚀

**Comment by nickcoutsos** [comment]
Great to hear!
