### ISSUE TITLE
Github Integration Not Working

### ISSUE THREAD

**Issue by Emilostuff** [nickcoutsos/keymap-editor#123]
I am unable to connect to Github. When clicking "Login with Github" the site stalls for a minute and then redirects to https://zmk-keymap-editor.fly.dev/github/authorize with error HTTP ERROR 502. Everything worked fine yesterday, but today it has suddenly stopped working.

**Comment by nickcoutsos** [comment]
Hi @Emilostuff, thanks for the heads-up. I haven't deployed any changes to the backend or frontend recently but it looks like my host had some issues this morning during a period that seems to coincide with your issue: https://status.flyio.net/incidents/f3jn8jh46nw6

![HTTP Response times chart showing a ~3-hour spike of responses taking more than two minutes to complete](https://github.com/nickcoutsos/keymap-editor/assets/1165066/a0545f40-1d64-474f-8bf7-9a6879f297c3)

That didn't look like fun. It looks like it's resolved, though, if you have a chance to try it again please let me know how it goes :)

**Comment by Emilostuff** [comment]
That makes a lot of sense. Thanks for checking up on it! Everything works fine again :)
