### ISSUE TITLE
Combo creation crash

### ISSUE THREAD

**Issue by pochoi** [nickcoutsos/keymap-editor#135]
When creating combo, if you try to assign a binding/behavior by clicking on the gray square of `&none`, it crashes!

Procedure:
1. Click the Combos tab
2. Click the Add New Comb button
3. Click the name, set a name and press enter
4. Click some keys in the mini keyboard
5. Click the big gray square of `&none` and select a binding/behavior in the pull down menu (then you change the `&none` to somethings else with a 🚫 sign sitting in the big gray square)
6. Click the Create button
7. Get a message asking for a new issue!

```
TypeError

t.properties.bindings.parsed.forEach is not a function

  https://nickcoutsos.github.io/keymap-editor/main.dc72c036eddc418b5345.js:2:90835
  https://nickcoutsos.github.io/keymap-editor/main.dc72c036eddc418b5345.js:2:90775
  https://nickcoutsos.github.io/keymap-editor/main.dc72c036eddc418b5345.js:2:94480
  https://nickcoutsos.github.io/keymap-editor/main.dc72c036eddc418b5345.js:2:94541
  webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:177:118
  webpack:///node_modules/react/cjs/react.production.min.js:25:207
  https://nickcoutsos.github.io/keymap-editor/main.dc72c036eddc418b5345.js:2:94016
  webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:166:136
  webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:215:269
```

How I can get around it is that:
1. Don't touch the big gray square with `&none` and create a combo.
2. Change the `&none` to a binding/behavior after the `&none` combo was created.

Yes, don't touch big gray square when creating combo. If you touch it and assign a `&none` when creating, it still produces the 🚫 sign and crashes.

**Comment by nickcoutsos** [comment]
Hi, thank you for the very detailed report! I've just pushed a fix!
