### ISSUE TITLE
Add globe keycode

### ISSUE THREAD

**Issue by AliQ80** [nickcoutsos/keymap-editor#143]
hello,

ZMK has introduced a globe keycode 3 months ago, I would like to suggest adding it to the keymap editor as it seems to not be available there (or I have missed it).

[zmk documentation](https://zmk.dev/docs/codes/applications) shows it in the last row in the first table (application control) as:
GLOBE, C_AC_NEXT_KEYBOARD_LAYOUT_SELECT : AC Next Keyboard Layout Select (Apple Globe) Consumer AC

thank you

**Comment by nickcoutsos** [comment]
If you mean this:

<img width="972" alt="Keymap Editor app screenshot showing a binding edit dialog with the globe keycode highlighted" src="https://github.com/nickcoutsos/keymap-editor/assets/1165066/5b54b8f7-c426-41df-bc86-5cb23c111a26">

it was only three days ago :)

**Comment by nickcoutsos** [comment]
Unrelated, I see you've been using the app with a reviung for some time now! If you're at all interested, I've more recently updated the layout data to more accurately represent the layout key rotation and sizing:

<img width="656" alt="Screen Shot 2023-10-02 at 11 47 59 AM" src="https://github.com/nickcoutsos/keymap-editor/assets/1165066/ead55ba7-a773-41ae-b199-cde52c24e47c">

If you'd like to use it you should be able to delete `config/reviung41.json` and the new layout would be picked up the next time you use the app.

**Comment by AliQ80** [comment]
Hi @nickcoutsos , I apologize for taking your time, you are correct it was 3 days ago, I don't know how I misread that,

I also don't know why globe didn't show up when I tried before.

Thank you for pointing out the reviung41 lay out, I will check it very soon

I really appreciate your work on this project, it's very under rated, and should have way much more recognition.
