### ISSUE TITLE
Feature request: remember UI settings on application restart

### ISSUE THREAD

**Issue by reshen** [nickcoutsos/keymap-editor#163]
Hi,

Use case: I keep the keymapp application open to help train myself on new key layouts; however, when the application restarts, I'd like it to reopen with previous window/application settings in tact:

- window size
- window location
- pinned state
- sidebar open/closed state

Thanks! :)

**Comment by nickcoutsos** [comment]
I think you're looking for https://github.com/zsa, this app isn't related to theirs or to the company at all.
