### ISSUE TITLE
Rotary encoder bindings not working

### ISSUE THREAD

**Issue by carlos-kassab-sp** [nickcoutsos/keymap-editor#177]
I've made sure my rotary encoder is working properly, the push button configuration works, but when I set up the rotation sensor it does not work.   For some reaso, the sensor bindings are not being picked up. I'm on a Sofle

Here's my repo https://github.com/KassabNova/zmk-config

**Comment by nickcoutsos** [comment]
Hi!

I don't have a Sofle myself so I may not be able to help a lot -- if Keymap Editor is able to save new `sensor-bindings` values and the ZMK build is still successful that's about all that can change on my end.

The first thing I'd look at is that the sensor devices are actually enabled but it looks like this is already the case in ZMK's shield definition.

Is there anything different about your hardware? Do different PCB versions maybe use different pins?

**Comment by nickcoutsos** [comment]
Oh, hey, you have to uncomment these two lines:

https://github.com/KassabNova/zmk-config/blob/2b6a9c3bf5f0537274be20b21d0739e7ac5afa47/config/sofle.conf#L8-L9

_(Make sure you're not just removing the `#` character, the space before `CONFIG_` needs to be removed as well)_

**Comment by carlos-kassab-sp** [comment]
Oh man, I was going insane. Ty so much.
Your tool is really cool, is there a way to donate a coffee as a thank you?
