### ISSUE TITLE
none of delete keycode working. 

### ISSUE THREAD

**Issue by FareziHanif** [nickcoutsos/keymap-editor#217]
tried 2 of delete keypress, but none of them work. Maybe sounds weird, but its act like home keycode. everytime i press delete key it just move the cursor to the first word of the line. any thought? 

Wanted to say thank you anyway, this is really a game changer for me who doesnt fully understand coding, so remapping from this website really boost my keymapping. Thank You so much!

**Comment by nickcoutsos** [comment]
There's no real trick to how keymap editor uses/assigns the keycodes. If it isn't something as mundane as the layout/matrix transform not matching (thus binding the key to a different location from what you're expecting) I'd check to make sure there isn't a mismatch with your OS character input (the locale for which it's interpreting your input).
