### ISSUE TITLE
Feature request: Enable import of german_aliases.h and others

### ISSUE THREAD

**Issue by gitlui** [nickcoutsos/keymap-editor#219]
Hi, 
I really love your tool. The only thing that is a problem for me right now is, that I can't create combos to write the German specific letters `äöüß`. 

In my own coded version of my layout, I've used a `#include "./german_aliases.h"` to have them available.

Is there a way that you could support the aliases? 

I think this will help a lot of people as most will use such aliases to get their language specific special characters.

I love your tool! Maybe I can help out with adding the functionality if you help me with some ideas where and how to put it.

**Comment by nickcoutsos** [comment]
Hi @gitlui,

Including arbitrary headers to look for additional behaviors/keycodes gets complicated (See [Keymap Editor Wiki::Preprocessor Support](https://github.com/nickcoutsos/keymap-editor/wiki/Preprocessor-Support) for a taste), but looking at your repository it looks like your needs for aliases aren't too complex. Have you looked at [zmk-locale-generator](https://github.com/joelspadin/zmk-locale-generator)? Its use is pretty common and static so if keymap editor detects one of the headers it'll included the extra keycodes/symbols (make sure to add the header file to your repository as well).

**Comment by gitlui** [comment]
Ah perfect. Thank you very much. Yesterday I went the route to replace all the aliases with the original keycodes to be able to use the editor. This worked, but it is cumbersome. I'll try your suggestion as it was essentially almost what I had before.
