### ISSUE TITLE
Support For The New Altar 1 Keyboard

### ISSUE THREAD

**Issue by HumbleGrumble87** [nickcoutsos/keymap-editor#231]
The Altar 1 is a keyboard created by the Electronic Materials Office and the very first pre-orders are just being received, myself included! It's a ZMK keyboard with a github repo here -> https://github.com/electronicmaterialsoffice/zmk 

I forked their repo, added my repo in your keymap editor, but I'm getting the "_config_ directory not found" error. The Altar 1 repo is just a fork of the ZMK repo, and the configs are located under 'app/boards/arm' and their are two relevant files for both the U.K and U.S keyboard layouts - I myself need 'altar_i_us'. Can you please make this available for the keymap editor so new Altar 1 owners don't have to mess around in a ZMK config? :)

**Comment by nickcoutsos** [comment]
Hi @HumbleGrumble87, sorry I missed this.

The app expects that you'll have a [zmk-config repo setup](https://zmk.dev/docs/config#user-config-folder) in which you have a `config/` folder containing keymap and other such overrides, and referencing another repo for the ZMK app itself.

In this case I think you'll want to clone [electronicmaterialsoffice/zmk-config](https://github.com/electronicmaterialsoffice/zmk-config) and work from that. It contains separate keymaps for US and UK layouts with matching JSON files so I think you should be able to use that straight away.

**Comment by HumbleGrumble87** [comment]
Thanks @nickcoutsos! That worked! Apologies for the silly question - still getting used to stuff. Thanks!

**Comment by nickcoutsos** [comment]
No worries, just glad there was an easy solution. I remember speaking with them a while back about the editor, cool to see they've launched!
