### ISSUE TITLE
Nested behaviour usage not included in usage count

### ISSUE THREAD

**Issue by sebmos** [nickcoutsos/keymap-editor#237]
The "Uses" column on the "Custom Behaviors" page does not include usages inside other behaviours, e.g. in mod-morph behaviours.

**Comment by nickcoutsos** [comment]
Thanks for the heads up I'll have to take a look at that. It should be checking references everywhere, including behaviors, but I may not have tested that exhaustively.

**Comment by sebmos** [comment]
If it helps, the specific scenario I've run into this is with a mod-morph behaviour that references a hold-tap behaviour as its "normal" binding. Possibly related: the hold-tap behaviour is defined before the mod-morph behaviour.

**Comment by nickcoutsos** [comment]
Sorry to have left this hanging, it ended up being a silly `map` vs `flatMap` mistake that only affected how I count references in behaviors. I did a quick test and it looks to be better now. Pushing changes momentarily.

**Comment by sebmos** [comment]
Perfect, works now!
