### ISSUE TITLE
The app is not loading my repo branch

### ISSUE THREAD

**Issue by liujoey** [nickcoutsos/keymap-editor#247]
I have a Adv360 forked reporitory, and I maintained a new branch "mine" that worked fine from day one.

Last time I use this tool was about three weeks ago and all was good. Today, all online editing tools, including this tool and the Adv360 tool, stopped reading my branch key maps; they show the default keymap no matter which branch I select.

My repo and branch link:
https://github.com/liujoey/Adv360-Pro-ZMK/tree/mine

There is no error message so I have no idea if this is related to reading issue caused by GitHub or it's some errors in my key map file.

Could someone help please?

**Comment by liujoey** [comment]
If I copy my key maps from the clipboard, the tool seems to work properly. It just can't read the correct maps from the GitHub repo. Maybe there was a recent authentication change from GitHub?

**Comment by nickcoutsos** [comment]
Hey -- I can take a look later this evening. It's curious that you're having this issue with Kinesis' editor as well. Could you clarify what you mean about it displaying the default keymap? Is that one of the other branches in your repo?

**Comment by pfilipp** [comment]
Hey I have been using your editor - marvellous job btw! - for quite some time and today I also noticed it loads mapping only from my main branch no matter which branch I will choose.

**Comment by nickcoutsos** [comment]
Sorry about this! I did some refactoring and overlooked a section where the branch parameter was still treated as optional. I pushed a fix and it should be resolved now, but please let me know if you're still encountering problems with it.

**Comment by liujoey** [comment]
It works perfectly now. Thank you.

**Comment by yangxing844** [comment]
hey, I think I have the same problem, the keymap editor does not load the correct layout and keymap for my keyboards, even when switch branch, my repo is https://github.com/yangxing844/zmk-config

**Comment by archseer** [comment]
Same here, it worked fine but now it's always using the same layout when switching between keyboards https://github.com/archseer/zmk-keys/

**Comment by nickcoutsos** [comment]
Thanks for this, the keyboard selection stuff was completely missed in my rushed testing. I just pushed a fix so when you have a chance please give it another try and let me know how it goes!

**Comment by yangxing844** [comment]
hey, now it read my keymap file correctly, thank you for such a fast response!
