### ISSUE TITLE
Editor editing wrong keyboard

### ISSUE THREAD

**Issue by binduwavell** [nickcoutsos/keymap-editor#248]
I edited some combos on the dasbob board here: https://github.com/binduwavell/zmk-config/ using the Keymap Editor site and it actually edited the common.keymap instead (https://github.com/binduwavell/zmk-config/commit/7f8f59646c287d13e4970b19655220e8d2019cde).

I have tried reloading the page and switching boards, it seems that no matter which keyboard I have selected, the UI only show what is in the common keyboard and not what is defined for dasbob or urchin. This used to work perfectly.

Any advice greatly appreciated!

**Comment by nickcoutsos** [comment]
Thanks for the heads up, I had a couple of other pings about this as well and just pushed a fix. Let me know if that takes care of things!

**Comment by binduwavell** [comment]
Worked, thank you!
