### ISSUE TITLE
Github login is not working 

### ISSUE THREAD

**Issue by ecambronerosaba** [nickcoutsos/keymap-editor#255]
![Screenshot 2024-09-19 at 4 32 59 PM](https://github.com/user-attachments/assets/578553c7-d4f1-485e-8f53-f79c4b0ac267)

When I go to the site this is what I get. I can't load any of my keymaps and relogging in doesn't work.

**Comment by Sellith** [comment]
yup, got the same problem here, i couldn't save so I refreshed the page, and I couldn't link back to my github

**Comment by nickcoutsos** [comment]
Thanks for the heads up!

Checking my server logs it seems that requests to GitHub's API are timing out. If my error logs are complete this started a little before you opened the issue and GitHub hasn't addressed it on their status page so I may have to poke around my host and see what's up.

**Comment by nickcoutsos** [comment]
Well that answers that: https://status.digitalocean.com/incidents/jl76cw5xjq9c

**Comment by nickcoutsos** [comment]
Ok, it should be resolved. I tested myself and keymaps are loading 👍
