### ISSUE TITLE
Feature: please support temper keyborad keymap

### ISSUE THREAD

**Issue by limichange** [nickcoutsos/keymap-editor#260]
## Photo
![C7454CC1-AF81-4D9C-961F-EE3E5B3643D9_4_5005_c](https://github.com/user-attachments/assets/d7038cba-4e1b-43e3-afd9-fd02047adb6b)

## Repo
https://github.com/raeedcho/temper

**Comment by nickcoutsos** [comment]
I'm not home at the moment, but it looks like they've got PCB files in that repo. If you take the `.kicad_pcb` file and import it via https://nickcoutsos.github.io/keymap-layout-tools/ you can use the resulting layout data by saving it to `config/info.json` in your repo.

**Comment by limichange** [comment]
🤩🤩🤩🤩🤩🤩
![CleanShot 2024-09-30 at 14 25 53@2x](https://github.com/user-attachments/assets/9f94c61f-9d92-4b44-ba1f-b16bac55fa23)

**Comment by limichange** [comment]
yeeeeeee!
![CleanShot 2024-09-30 at 14 28 48@2x](https://github.com/user-attachments/assets/5d118367-7f16-41b7-835c-b7e48d269414)
