### ISSUE TITLE
Command failed (Running Locally)

### ISSUE THREAD

**Issue by or-agami** [nickcoutsos/keymap-editor#27]
Hi,

I tried to install the app with [this guide](https://github.com/nickcoutsos/keymap-editor/blob/d61a71b2882e203d3c2dde9532e404f54b122986/running-locally.md) and I faced with Error "Command failed: npm run build-watch", any advice? 

![תמונה](https://user-images.githubusercontent.com/57838085/163279233-006a0e58-54ee-47ff-b78d-899c3ca2ff82.png)

**Comment by nickcoutsos** [comment]
That's... that's new to me. Looking into the `ERR_OSSL_EVP_UNSUPPORTED` pulls up some issues:

* https://www.bswen.com/2021/11/reactjs-ERR_OSSL_EVP_UNSUPPORTED_error_solution.html
* https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

I haven't seen this come up, I'm on Node v17.8.0, but would you want to try `export NODE_OPTIONS=--openssl-legacy-provider` suggestion and let me know how that goes? If it doesn't pass into the build-watch process you may need to add it to the env mapping in `api/routes/application.js` line ~16.

**Comment by nickcoutsos** [comment]
What's weird is that I keep seeing mention of this issue relating to webpack@4 but I've got version 5 in the dependencies. I see webpack-cli is a major version of 4, wonder if that's got something to do with this.

**Comment by nickcoutsos** [comment]
@or-agami hi, was there any luck with the above links?

**Comment by or-agami** [comment]
@nickcoutsos Actually I didn't tried again I've been busy at work.
I'll update as soon as I have something, thanks!

**Comment by or-agami** [comment]
I think I messed up with the SSL files somehow

**Comment by nickcoutsos** [comment]
Oh that's an interesting problem. Not sure what to do about that.
