### ISSUE TITLE
Some Unicode characters are not displayed correctly

### ISSUE THREAD

**Issue by Dimentium** [nickcoutsos/keymap-editor#43]
Hi!

The characters for the arrows (left, up, down, right) and the DELETE button are not displaying properly.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/5391420/182684488-bc954a1e-5b78-4f37-a9ee-437d817ca292.png">

I installed Quicksand font, checked in Safari and Firefox. 
The results are the same.

**Comment by nickcoutsos** [comment]
You know, I've seen other people have this issue but haven't investigated it yet myself. Are you on Windows?

I had assumed that the Unicode glyphs I picked would work for everybody, but most likely my OS falling back to a font where they're present while yours has no alternative.

Recently I've made some changes to my keycode definitions and turned the symbol/icon mappings into overlays something like
- base keycode definitions (e.g. `"RIGHT_ARROW"`)
- unicode glyphs (whichever ones I picked out that seemed useful, e.g. `⮐`)
- Windows-specific font-awesome glyphs (right now that's just the Windows logo for the GUI key)
- macOS-specific font-awesome glyphs (for the cmd and option keys)

At some point I should replace at least the problematic unicode glyphs with font-awesome alternatives, but in the meantime there are settings you can use to hopefully avoid the situation of blank symbols:
<img width="616" alt="Screen Shot 2022-08-03 at 5 25 30 PM" src="https://user-images.githubusercontent.com/1165066/182715046-248c9f6e-40cd-42e0-8ba8-073fa9f2b6d4.png">

**Comment by nickcoutsos** [comment]
Ah, hell, I just noticed that the [delete icon](https://fontawesome.com/icons/delete-right?s=solid) isn't part of the font-awesome free set. That's a shame, I'll have to look for something else for that or else just show `DEL` again.

I suppose I could get ridiculous and have it render the backspace symbol flipped around...

**Comment by Dimentium** [comment]
Im on MacOS.

also on Linux arrows displayed ok:
![image](https://user-images.githubusercontent.com/5391420/182827875-6b4d0fcb-1a10-4473-a428-dc0f29a67085.png)

I have not Windows right now for check that :(

**Comment by nickcoutsos** [comment]
I think the fact that we're both on macOS and getting different results is enough to convince me to do something. I did like those arrows but font-awesome has some that look pretty much the same so there's no reason now to switch to that. I can get a fix out later tonight.

**Comment by nickcoutsos** [comment]
Pushed some changes.

Arrows are now using font-awesome, and I've cheekily implemented the delete icon by flipping the backspace icon around. I think the only remaining "exotic" unicode glyphs are for command, option, shift, and enter. The latter two seem to be rendering fine in your screenshot, so we're probably fine but let me know if you run into other issues!

**Comment by Dimentium** [comment]
Awesome!
Thank you!! :)

<img width="911" alt="image" src="https://user-images.githubusercontent.com/5391420/183018301-ab054a18-2989-4b88-8261-0c374577b266.png">

**Comment by Dimentium** [comment]
> Pushed some changes.
> 
> Arrows are now using font-awesome, and I've cheekily implemented the delete icon by flipping the backspace icon around. I think the only remaining "exotic" unicode glyphs are for command, option, shift, and enter. The latter two seem to be rendering fine in your screenshot, so we're probably fine but let me know if you run into other issues!

Note that there is still a bad symbol here in the settings:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/5391420/183018957-5aa68a7a-2d8b-4757-805a-f0232b3b4a70.png">

**Comment by nickcoutsos** [comment]
Thanks, I'll make a note to update that as well!
