### ISSUE TITLE
Feature Request: Support for user-defined behaviors.json

### ISSUE THREAD

**Issue by ankushg** [nickcoutsos/keymap-editor#51]
I've got a board that has some custom behaviors defined in firmware, that haven't yet made it into the upstream zmk firmware.

It would be really cool if the app could somehow pick up a `user-behaviors.json` file if it's in the keymap repo, and merge it with the `zmk-behaviors.json` that it uses to determine behaviors. 

I imagine this might also allow users to custom-define things like `HYPER`/`MEH` and provide it in the `includes` block (related to this: https://github.com/nickcoutsos/keymap-editor/discussions/50#discussioncomment-3754829)

**Comment by nickcoutsos** [comment]
Hi @ankushg, I got around to adding behavior editing which isn't exactly connected to custom keycodes but it does add more flexibility for behaviors.
