### ISSUE TITLE
Prompt user for commit message

### ISSUE THREAD

**Issue by nickcoutsos** [nickcoutsos/keymap-editor#6]
Instead of just posting `"Updated keymap"` when making commits on the user's repo, the app could prompt them for a description of the changes and submit that in the commit instead.

**Comment by Dimentium** [comment]
hi!
may be not prompt, but input box near "commit changes" button?

**Comment by Dimentium** [comment]
very nice!
![image](https://user-images.githubusercontent.com/5391420/182584478-2560670d-7df7-4dde-aa88-a844a86adc91.png)

thank you!!

**Comment by nickcoutsos** [comment]
Glad you like it! It could do with some better styling but that can come later on, this was a pretty quick implementation.
