### ISSUE TITLE
Key toggle `&kt` not supported by UI?

### ISSUE THREAD

**Issue by nickcoutsos** [nickcoutsos/keymap-editor#60]
### Discussed in https://github.com/nickcoutsos/keymap-editor/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **Richiban** October  9, 2022</sup>
It seems that key toggle isn't supported by the tool? It doesn't appear in the behaviour drop-down and if `&kt` appears in the keymap file the UI displays an error.</div>

**Comment by nickcoutsos** [comment]
@Richiban I just pushed a build with `&kt` added if you'd like to confirm

**Comment by Richiban** [comment]
Yep, can confirm my key toggle now appears in the UI and I can create a new one. Thanks for the quick turnaround!
