### ISSUE TITLE
Encoders appear to have been defined backwards

### ISSUE THREAD

**Issue by Richiban** [nickcoutsos/keymap-editor#61]
It appears that the UI gets _clockwise_ and _anti-clockwise_ the wrong way round. See screenshot for how I've had to define my encoders incorrectly int order to get the keycodes to show up correctly in the keymap file:

![Screenshot 2022-10-10 at 14 39 11](https://user-images.githubusercontent.com/668303/194879542-50020ea0-96d2-4049-a82d-efd87a98d6c1.png)

The above produces the following keymap:

![Screenshot 2022-10-10 at 14 40 37](https://user-images.githubusercontent.com/668303/194879700-d69206e7-392a-4b20-a2ca-c92b06e9eaf0.png)

**Comment by Richiban** [comment]
On having a second look, it appear they may have wired my encoders up backwards! The ZMK docs do say that the CW goes first, then the CCW key (so, in my case, it should be `<&inc_dec_kp DOWN UP &inc_dec_kp LA(RIGHT) LA(LEFT)>` instead. Might be helpful if someone else can confirm this!

**Comment by nickcoutsos** [comment]
You had me a little worried there! I do indeed swap the widget order, displaying the decrement binding first, but it _should_ be mapping to the correct binding cell in the devicetree keymap. I would double-check this myself, but I don't have any encoders and all of my keyboards are hand-wired.

I'll leave this open for now if you're or anyone else can add more details!
