### ISSUE TITLE
Keymap-editor stuck on Waiting for API..

### ISSUE THREAD

**Issue by Designbykivi** [nickcoutsos/keymap-editor#67]
Heya, tried opening up the [web keymap-editor](https://nickcoutsos.github.io/keymap-editor/), but it just says "Waiting for API..". Tried several browsers and even on my phone, but the issues persists.

Alternatively I tried to set up the editor locally by following the [readme](https://github.com/nickcoutsos/keymap-editor/blob/main/running-locally.md). Managed to start the npm app by adding `PORT=8081 node index.js` at the end of my `.env `filebut eventually ended up in the same situation where it just says "Waiting for API.." and nothing happens.

**Comment by nickcoutsos** [comment]
Thanks for the heads up, that's really weird. Something seems to be up with the provider, I'll see what I can do once I'm home from work and let you know.

**Comment by nickcoutsos** [comment]
I haven't done anything but it looks like it successfully started itself back up... hopefully it stays that way, there haven't been any code or configuration changes so if it's something on the provider's side I haven't seen them confirm it.
