### ISSUE TITLE
sticky key do not show again

### ISSUE THREAD

**Issue by magagne** [nickcoutsos/keymap-editor#72]
hi there,

the problem came back again about the sticky key, I cannot do configuration in the UI.

<img width="475" alt="Screenshot 2022-12-15 at 11 32 34 PM" src="https://user-images.githubusercontent.com/117384104/208024056-f696fd6b-ec01-457f-ab74-1933f107a7c4.png">

<img width="583" alt="Screenshot 2022-12-15 at 11 37 30 PM" src="https://user-images.githubusercontent.com/117384104/208024057-2152195a-f1ef-4dcc-986c-5081a374d482.png">

cheers.
Matthieu.

**Comment by nickcoutsos** [comment]
Sorry about that, I've been trying to merge in some work that's been sitting around for a while. I've deployed a fix.

**Comment by magagne** [comment]
lol regression bug...that can happen to anybody do not be sorry ;-)
