### ISSUE TITLE
Different layout between layers

### ISSUE THREAD

**Issue by DMAgit** [nickcoutsos/keymap-editor#80]
Hey, trying to make a layout for the Ferris Sweep. The automatic generator failed, but I made one of my own. I thought I did something wrong and that it wasn't working, but I noticed that it works as intended on the non-base layers. See screenshots attached.

Base layer:
![Base layer](https://user-images.githubusercontent.com/44362174/212423657-1bc279aa-b697-478f-9fce-4f9d4635e782.png)

Num layer:
![Num layer](https://user-images.githubusercontent.com/44362174/212423720-2b93a48e-7984-45d5-8dfd-6f034bfa33c9.png)

Also see the info.json file [here](https://github.com/DMAgit/zmk-config/blob/7fb6d31e9d105ef7e45901ddfbc3b86f7789cf3d/config/info.json)

**Comment by nickcoutsos** [comment]
The layout is fine, the keymap editor doesn't support the macro you're trying to use for homerow mods.

**Comment by DMAgit** [comment]
I'm sorry, could you explain how I could fix it? I'm using the base layout that comes with ZMK for the Sweep. What should I change so that it works correctly?

**Comment by nickcoutsos** [comment]
Your keymap https://github.com/DMAgit/zmk-config/commit/23a5288975ee3cb80a0edaa6dcfd74fca7e7c4eb#diff-01ae956db6950cdbe4887d3c731965e52a1bd1071e198bcf82b738c1cf1919e6R43 references some macro functions to simplify the bindings for homerow mods (https://github.com/DMAgit/zmk-config/commit/23a5288975ee3cb80a0edaa6dcfd74fca7e7c4eb#diff-01ae956db6950cdbe4887d3c731965e52a1bd1071e198bcf82b738c1cf1919e6R9-R10)

To you use the editor with this keymap you would have to replace the use of that macro with the actual bindings bindings:

```diff
-HRML(A,        S,         D,         F)     &kp G          &kp H      HRMR(J,        K,         L,        SQT)
+&ht LSHFT A   &ht LALT S   &ht LCTL D   &ht LGUI F   &kp G          &kp H      &ht RGUI J   &ht RCTRL K   &ht RALT L   &ht RSHFT SQT
```

Once you do that it should be able to parse the keymap bindings correctly.

**Comment by nickcoutsos** [comment]
@DMAgit I may have gotten the diff syntax wrong, you weren't meant to include the `+` at the beginning of the line.

**Comment by DMAgit** [comment]
Yes, fixed that and a couple of other small things :) I think I have a better understanding of it now and its fixed. Thank you for your help 👍

**Comment by nickcoutsos** [comment]
Awesome, glad it worked out!
