### ISSUE TITLE
[BUG] clear my keymap after commit.

### ISSUE THREAD

**Issue by kuolemax** [nickcoutsos/keymap-editor#84]
this is my zmk repository: [zmk-swoop](https://github.com/kuolemax/zmk-swoop)

after commit:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/25677528/217786595-1c37502a-bbe6-400d-a085-2785195cd58b.png">

and my keymap file:
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/25677528/217786731-c021eea3-258a-40be-b1a3-a82d2554faac.png">

**Comment by nickcoutsos** [comment]
Hi!

Thanks for bringing this to my attention, I'm sorry to see this causing problems for you. I'm noticing that other parts of the keymap appear to be ok (`sensor-bindings` isn't blanked out), and after looking at your layout definition it appears that you have the `"col"` and `"row"` property names swapped.

There's definitely a bug here in my code, I _think_ it would relate to the gaps in row values, but even without that you would end up with jumbled up bindings. Swap `row` and `col` (the other properties all look correct, you can leave them alone) and let me know how that goes.

**Comment by kuolemax** [comment]
Thank you very much for your help, it is indeed caused by writing `col` and `row` in reverse, and now it works very well. Thanks again!
