### ISSUE TITLE
Macros are being deleted

### ISSUE THREAD

**Issue by danielo515** [nickcoutsos/keymap-editor#95]
Hello again.
For some reason, every time I add a macro the last macro in the list gets deleted. This seems to happen if I add two macros.

Maybe it's because I have all the macros inside a single macro block?

**Comment by nickcoutsos** [comment]
I just pushed up a fix for this so it should be able to handle behaviors and macros even when they aren't all in the same container. (Of course I'd still recommend keeping them together)

**Comment by danielo515** [comment]
Hello @nickcoutsos , thanks for taking care of this so quick. I think it makes more sense if I reorganise my macros and behaviours into one node. As I mentioned in another issue I am totally new to ZMK and I am just using as a base what the glove80 editor generates.

I just noticed however, that the latest version of the app has some trouble finding my macros? The keys appear to not be tied to any macro when I load my keymap, and when I go to the selection list of available "things" this is what I see 
![image](https://user-images.githubusercontent.com/2270425/229464350-2b8c7a9f-7bd9-4cb1-aff4-961b126bede6.png)

So somehow the names are not being parsed, and that indeed makes the keys not match the name of the macro.
This is how my keymap looks currently: https://github.com/danielo515/glove80-zmk-config/tree/main/config/glove80.keymap

**Comment by nickcoutsos** [comment]
Thanks, fixed now.
